apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: default
  labels: 
    app: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-deployment
  template:
    metadata:
      labels:
        app: client-deployment
    spec:
      containers:
      - name: client
        image: byoa4-client:latest
      imagePullSecrets:
        - name: regcred
      ports:
      - containerPort: 3000
