apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: default
spec:
  selector:
    app: client-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
  type: NodePort
