apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: default
spec:
  selector:
    app: client-deployment
  ports:
  - protocol: TCP
    port: {{ .Values.ports.servicePort }}
    targetPort: {{ .Values.ports.containerPort }}
    nodePort: {{ .Values.ports.nodePort }}
  type: NodePort
