version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:3001"
    env_file:
      - .env
  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server  # The client depends on the server
networks:
  default:
    name: my-network
