version: '3'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  server:
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:3001"
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongo

  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:3000"
    depends_on:
      - server  # The client depends on the server

  worker:  
    build:
      context: ./worker 
    ports:
      - "${WORKER_PORT}:3002"  
    env_file:
      - .env
    depends_on:
      - rabbitmq

  mongo:
    image: mongo
    container_name: mongodb-local
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  default:
    name: my-network
