version: '3'
services:
  server:
    image: server-image
    ports:
      - "3001:3001"
  client:
    image: client-image
    ports:
      - "3000:3000"
    depends_on:
      - server
networks:
  default:
    name: my-network