apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stclass
  namespace: default
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi