variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts the very simple Docker container
systemd:
  units:
    - name: docker.service
      enabled: true

    # Docker container started as a systemd service
    - name: helloworld.service
      enabled: true
      contents: |
        [Unit]
        Description=Hello World
        After=docker.service
        Requires=docker.service

        [Service]
        TimeoutStartSec=0
        ExecStartPre=-/usr/bin/docker kill helloworld
        ExecStartPre=-/usr/bin/docker rm helloworld
        ExecStartPre=/usr/bin/docker pull ${imagename}
        ExecStart=/usr/bin/docker run --name helloworld -p 80:80 ${imagename}

        [Install]
        WantedBy=multi-user.target

    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=Bootstrap K3s
        After=network-online.target

        [Service]
        ExecStart=/usr/local/bin/bootstrap_k3s.sh

        [Install]
        WantedBy=multi-user.target
