variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}


# This starts the very simple Master K8s nd
systemd:
  units:
    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=Master K8S
        Documentation=https://k3s.io
        After=network.target

        [Service]
        Environment="INSTALL_K3S_EXEC=--cluster-init"
        Environment="K3S_TOKEN=${k3s_token}"
        ExecStart=/usr/bin/bash -c "curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server --token=${k3s_token} --write-kubeconfig-mode=777 --tls-san 195.169.23.130' sh -s -"
        Type=notify
        Restart=always
        RestartSec=5
        StartLimitInterval=0
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target
    - name: install-helm.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Helm
        After= k3s.service
        [Service]
        Type=oneshot
        Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
        ExecStartPre=/usr/bin/bash -c "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        ExecStartPre=/usr/bin/bash -c "chmod 700 get_helm.sh"
        ExecStart=/usr/bin/bash -c "HELM_INSTALL_DIR=/opt/bin ./get_helm.sh"        

        [Install]
        WantedBy=multi-user.target
    - name: storage-stuff.service
      enabled: true
      contents: |
        [Unit]
        Description= Storage stuff Service
        After= install-helm.service
        Requires=k3s.service network.target 
        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/bash -c "git clone https://github.com/kubernetes/cloud-provider-openstack /home/core/cloud"   
        ExecStartPre=/usr/bin/bash -c "cd /home/core/cloud && sudo git checkout tags/v1.27.3"
        ExecStart=/usr/bin/bash -c "git clone https://github.com/iknek/testVMRepo.git /home/core/test"

        [Install]
        WantedBy=multi-user.target
