variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts the very simple worker K8s nd
systemd:
  units:
    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=worker K8S
        Documentation=https://k3s.io
        After=network.target

        [Service]
        ExecStartPre=-/usr/bin/systemctl stop k3s
        ExecStartPre=-/usr/bin/systemctl disable k3s
        ExecStartPre=-/usr/bin/rm -rf /var/lib/rancher/k3s
        ExecStartPre=/usr/bin/curl -sfL https://get.k3s.io -o /tmp/k3s-install.sh
        ExecStartPre=/usr/bin/chmod +x /tmp/k3s-install.sh
        ExecStartPre=/usr/bin/bash /tmp/k3s-install.sh
        ExecStart=/usr/local/bin/k3s agent --server https://10.10.0.94:6443 token=master
        Type=notify
        Restart=always
        RestartSec=5
        StartLimitInterval=0
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target