variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts/installs k3s
systemd:
  units:
    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=K3S service
        After=network-online.target

        [Service]
        Type=exec
        ExecStartPre=/usr/bin/curl -sfL https://get.k3s.io -o /opt/k3s_install.sh
        ExecStartPre=/usr/bin/chmod +x /opt/k3s_install.sh
        ExecStart=/opt/k3s_install.sh --disable=traefik --disable=local-storage
        ExecStartPost=/usr/bin/echo "K3s Installed Successfully" > /dev/console

        [Install]
        WantedBy=multi-user.target
