variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts the very simple Master K8s nd
systemd:
  units:
    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=Master K8S
        Documentation=https://k3s.io
        After=network.target

        [Service]
        Environment="INSTALL_K3S_EXEC=--cluster-init"
        Environment="K3S_TOKEN=${k3s_token}"
        ExecStart=/usr/bin/bash -c "curl -sfL https://get.k3s.io | K3S_TOKEN=${k3s_token} sh -s server"
        Type=notify
        Restart=always
        RestartSec=5
        StartLimitInterval=0
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target
    - name: install-helm.service
      enabled: true
      contents: |
        [Unit]
        Description=Install Helm
        After= k3s.service
        [Service]
        Type=oneshot
        Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
        ExecStartPre=/usr/bin/bash -c "curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
        ExecStartPre=/usr/bin/bash -c "chmod 700 get_helm.sh"
        ExecStart=/usr/bin/bash -c "HELM_INSTALL_DIR=/opt/bin ./get_helm.sh"        

        [Install]
        WantedBy=multi-user.target
    - name: storage-stuff.service
      enabled: true
      contents: |
        [Unit]
        Description= Storage stuff Service
        After= install-helm.service
        Requires=k3s.service network.target 
        [Service]
        Type=oneshot
        ExecStartPre=/usr/bin/bash -c "git clone https://github.com/kubernetes/cloud-provider-openstack /home/core/cloud"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/cloud && sudo git checkout tags/v1.27.3"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/ && sudo kubectl create secret -n kube-system generic cloud-config --from-file=cloud.conf"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/cloud && rm manifests/cinder-csi-plugin/csi-secret-cinderplugin.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/cloud && sudo kubectl -f manifests/cinder-csi-plugin/ apply"
        ExecStart=/usr/bin/bash -c "cd /home/core/ && sudo kubectl apply -f cinder-pv.yaml && sudo kubectl apply -f cinder-pvc.yaml"

        [Install]
        WantedBy=multi-user.target
    - name: setup-helms.service
      enabled: true
      contents: |
        [Unit]
        Description=Setup Helms
        Requires=install-helm.service
        After=install-helm.service network.target
        [Service]
        Type=oneshot
        Environment="PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
        ExecStartPre=/usr/bin/bash -c "until helm version; do echo 'Waiting for Helm to be ready'; sleep 5; done"
        ExecStartPre=/usr/bin/bash -c "git clone https://github.com/iknek/testVMRepo.git /home/core/test"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm repo add bitnami https://charts.bitnami.com/bitnami --kubeconfig=/etc/rancher/k3s/k3s.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx --kubeconfig=/etc/rancher/k3s/k3s.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm repo update"
        ExecStartPre=/usr/bin/bash -c "for i in {1..5}; do sudo kubectl cluster-info && sudo helm install my-mongodb bitnami/mongodb --set auth.rootPassword=${mongopass},persistence.existingClaim=test-volume --kubeconfig=/etc/rancher/k3s/k3s.yaml && break || sleep 15; done"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm install rabbit --set auth.username=${rabbituser},auth.password=${rabbitpass},auth.erlangCookie=secretcookie bitnami/rabbitmq --kubeconfig=/etc/rancher/k3s/k3s.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm install ingress-nginx ingress-nginx/ingress-nginx --kubeconfig=/etc/rancher/k3s/k3s.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo kubectl rollout status deployment/ingress-nginx-controller -n default"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo kubectl apply -f secrets.yaml && sudo kubectl apply -f configmap.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm install server server-0.1.0.tgz --kubeconfig=/etc/rancher/k3s/k3s.yaml"
        ExecStartPre=/usr/bin/bash -c "cd /home/core/test && sudo helm install worker worker-0.1.0.tgz --kubeconfig=/etc/rancher/k3s/k3s.yaml"       
        ExecStart=/usr/bin/bash -c "cd /home/core/test && sudo helm install client client-0.1.0.tgz --kubeconfig=/etc/rancher/k3s/k3s.yaml >> /var/log/helm_install.log 2>&1"

        [Install]
        WantedBy=multi-user.target

