variant: flatcar
version: 1.0.0

# This configures the user account
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ${sshkey}

# This starts the very simple Master K8s nd
systemd:
  units:
    - name: k3s.service
      enabled: true
      contents: |
        [Unit]
        Description=Master K8S
        Documentation=https://k3s.io
        After=network.target

        [Service]
        Environment="K3S_TOKEN=K10c45f0114812572fba0f917c68a963be4029aa0188fef3c1acaab35adc84da14a::server:93a13f6c263675c087dbb756d14b41a7"
        ExecStartPre=/usr/bin/curl -sfL https://get.k3s.io -o /tmp/k3s-install.sh
        ExecStartPre=/usr/bin/chmod +x /tmp/k3s-install.sh
        ExecStartPre=/usr/bin/bash /tmp/k3s-install.sh
        ExecStart=/usr/local/bin/k3s server
        Type=notify
        Restart=always
        RestartSec=5
        StartLimitInterval=0
        Delegate=yes
        LimitNOFILE=1048576
        LimitNPROC=infinity
        LimitCORE=infinity
        TasksMax=infinity

        [Install]
        WantedBy=multi-user.target
    - name: apply-cinder-storageclass.service
      enabled: true
      contents: |
        [Unit]
        Description=Apply Cinder StorageClass
        After=k3s.service

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/bash -c "echo 'apiVersion: storage.k8s.io/v1\nkind: StorageClass\nmetadata:\n  name: cinder-basic\nprovisioner: kubernetes.io/cinder\n' > /home/core/cinder-storageclass.yaml && sudo kubectl apply -f /home/core/cinder-storageclass.yaml"

        [Install]
        WantedBy=multi-user.target  