apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: default
  labels: 
    app: server-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: server-deployment
  template:
    metadata:
      labels:
        app: server-deployment
    spec:
      containers:
      - name: server
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        envFrom:
        - configMapRef:
            name: app-config  
        - secretRef:
            name: app-secret
        ports:
        - containerPort: {{ .Values.ports.containerPort }}