apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
spec:
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
      nodePort: {{ .Values.ports.nodePort }}
  type: LoadBalancer