apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: default
spec:
  selector:
    app: server-deployment
  ports:
    - protocol: TCP
      port: 81
      targetPort: 3001
      nodePort: 30081
  type: LoadBalancer