apiVersion: v2
name: my-app
version: 0.1.0
dependencies:
  - name: mongodb
    version: "14.0.1"
    repository: "https://charts.bitnami.com/bitnami"
  - name: rabbitmq
    version: "12.1.7"  
    repository: "https://charts.bitnami.com/bitnami"
