apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  selector:
    component: worker
  ports:
    - protocol: TCP
      port: {{ .Values.ports.servicePort }}
      targetPort: {{ .Values.ports.containerPort }}
