apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          envFrom:
          - configMapRef:
              name: app-config  
          - secretRef:
              name: app-secret
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
